// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/18/2025, 5:06:41 PM
const configMerger = require("/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/plugins/**/*.{js,ts,mjs}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/composables/**/*.{js,ts,mjs}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/utils/**/*.{js,ts,mjs}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/vishalpulikottil/Instinctive Clients/Nova (CI)/nova-course-creator-ai/app.config.{js,ts,mjs}"] } }));

module.exports = config
